---
version: "3.8"

services:
  zookeeper:
    image: zookeeper:3.4.12
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:5.0.1-1
    restart: always
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://localhost:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  cassandra:
    image: cassandra:3.11.6
    volumes:
      - ./KafkaTrigger.yml:/etc/cassandra/triggers/KafkaTrigger.yml
      - ./cassandra-trigger-0.0.1-SNAPSHOT.jar:/etc/cassandra/triggers/trigger.jar
    command: ["cassandra", "-f"]
    ports:
        - "7000:7000"
        - "9042:9042"
    depends_on:
      - kafka
